/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TransactionRouteImport } from './routes/transaction'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DisputeRouteImport } from './routes/dispute'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ActiveRouteImport } from './routes/active'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionRoute = TransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeRoute = DisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRoute = ActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dispute': typeof DisputeRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/transaction': typeof TransactionRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dispute': typeof DisputeRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/transaction': typeof TransactionRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dispute': typeof DisputeRoute
  '/home': typeof HomeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/transaction': typeof TransactionRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active'
    | '/chat'
    | '/create'
    | '/dispute'
    | '/home'
    | '/payment'
    | '/profile'
    | '/review'
    | '/transaction'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active'
    | '/chat'
    | '/create'
    | '/dispute'
    | '/home'
    | '/payment'
    | '/profile'
    | '/review'
    | '/transaction'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/active'
    | '/chat'
    | '/create'
    | '/dispute'
    | '/home'
    | '/payment'
    | '/profile'
    | '/review'
    | '/transaction'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveRoute: typeof ActiveRoute
  ChatRoute: typeof ChatRoute
  CreateRoute: typeof CreateRoute
  DisputeRoute: typeof DisputeRoute
  HomeRoute: typeof HomeRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  TransactionRoute: typeof TransactionRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction': {
      id: '/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof TransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute': {
      id: '/dispute'
      path: '/dispute'
      fullPath: '/dispute'
      preLoaderRoute: typeof DisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveRoute: ActiveRoute,
  ChatRoute: ChatRoute,
  CreateRoute: CreateRoute,
  DisputeRoute: DisputeRoute,
  HomeRoute: HomeRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  TransactionRoute: TransactionRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
